### ISSUE TITLE
Convert shiny.tag/shiny.tag.list objects to components?

### ISSUE THREAD

**Issue by cpsievert** [plotly/dashR#1]
It'd be cool if users could reuse their shiny UIs for a dash application, and more generally, insert shiny.tag/shiny.tag.list objects (from [htmltools](https://github.com/rstudio/htmltools)) inside their dash layout. 

Since [dash doesn't (yet) support arbitrary HTML](https://github.com/plotly/dash/issues/118), perhaps we could try to support a subset of these objects (i.e., everything but `htmltools::HTML()`), by translating each tag to a component.

As a side note, I wonder what shiny/htmltools does to prevent cross-side scripting (as discussed [here](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml))

**Comment by rpkyle** [comment]
This is not part of the current feature roadmap; closing for now.
