### ISSUE TITLE
dashr documentation down

### ISSUE THREAD

**Issue by bborens** [plotly/dashR#106]
Can't open the documentation:

https://dashr.plot.ly

returns

ERROR: 'names' attribute [11] must be the same length as the vector [10]

**Comment by rpkyle** [comment]
> Can't open the documentation:
> 
> https://dashr.plot.ly
> 
> returns
> 
> ERROR: 'names' attribute [11] must be the same length as the vector [10]

@bborens Thanks for your interest in Dash for R! 🙂 Could you try clearing your browser cache and reloading the page? 

This has happened to a few of us at Plotly who loaded the docs prior to the registration of the current DNS name. Once your cache is clean, the page should load as before.

**Comment by bborens** [comment]
Thank you so much for responding so quickly! (Especially to such a novice problem heh!) 

Looking forward to using this! Excellent work!

**Comment by rpkyle** [comment]
> Thank you so much for responding so quickly! (Especially to such a novice problem heh!)
> 
> Looking forward to using this! Excellent work!

Glad to hear it, and thanks!
