### ISSUE TITLE
Hello world example graph broken: missing plotly dependency

### ISSUE THREAD

**Issue by tomecki** [plotly/dashR#108]
When running sample dashr app from either [docs](https://dashr.plot.ly/getting-started) or [readme](https://github.com/plotly/dashR#hello-world-example-using-dccgraph) plots fail to render.

Console output produces:
```
warning: The dependency path '' within the 'dashCoreComponents' package is invalid; cannot find 'plotly-1.48.3.min.js'. from NULL
```

Chrome devtools errors with:
```
react-dom.production.min.js?v=16.8.6&m=1564556296:117 ReferenceError: Plotly is not defined
    at t.value (Graph.react.js:108)
    at t.value (Graph.react.js:209)
    at qi (react-dom.production.min.js?v=16.8.6&m=1564556296:130)
    at ui (react-dom.production.min.js?v=16.8.6&m=1564556296:133)
    at react-dom.production.min.js?v=16.8.6&m=1564556296:158
    at unstable_runWithPriority (react.production.min.js?v=16.8.6&m=1564556296:27)
    at Vc (react-dom.production.min.js?v=16.8.6&m=1564556296:158)
    at Sc (react-dom.production.min.js?v=16.8.6&m=1564556296:158)
    at Z (react-dom.production.min.js?v=16.8.6&m=1564556296:156)
    at Kc (react-dom.production.min.js?v=16.8.6&m=1564556296:155)
```
I am running R 3.6.1 with all required dependencies from README installed.

**Comment by rpkyle** [comment]
@tomecki Sorry about that; I believe I've resolved the error you reported in plotly/dash-core-components#591. Would you mind reinstalling `dashCoreComponents` and trying again?

**Comment by squeezer44** [comment]
@rpkyle 
I already had a similar problem:
`warning: The dependency path '' within the 'dashCoreComponents' package is invalid; cannot find 'plotly-1.48.3.min.js'. from NULL`

After I reinstalled `dashcorecomponents` it was solved.
Thx for the fix.

**Comment by rpkyle** [comment]
Thanks @squeezer44! 

I’ll hold off on closing for a bit to give @tomecki to confirm that I’ve resolved the issue as noted.

**Comment by rpkyle** [comment]
P.S. I took the opportunity to add a package vignette for `dashCoreComponents`, I hope it’s useful as a supplement to the extensive online documentation.

**Comment by tomecki** [comment]
@rpkyle thanks for quick response - I confirm hello world now runs smooth as butter :+1:

**Comment by rpkyle** [comment]
@tomecki Great! Thanks again for opening the issue. I'll close it now, but please let us know if you run into any other trouble.
