### ISSUE TITLE
change pruned_errors to dev_tools_prune_errors

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dashR#112]
in https://github.com/plotly/dash/pull/860 I implemented a similar feature to `pruned_errors` on the Python side. But for consistency I prefixed it `dev_tools_`, and I find it clearer as a verb "prune" rather than an adjective "pruned." Can we change the R version to match?

**Comment by rpkyle** [comment]
> in [plotly/dash#860](https://github.com/plotly/dash/pull/860) I implemented a similar feature to `pruned_errors` on the Python side. But for consistency I prefixed it `dev_tools_`, and I find it clearer as a verb "prune" rather than an adjective "pruned." Can we change the R version to match?

For sure, I can open a PR to close this issue tomorrow.

**Comment by rpkyle** [comment]
Closed by #113.
