### ISSUE TITLE
How to embed a full HTML document in Dash for R?

### ISSUE THREAD

**Issue by heoa** [plotly/dashR#117]
I tried to embed the HTML ```test.html``` with multiple commands such as ```htmlIFrame``` but nothing gets rendeded. What is the proper way to embed full HTML document into dashR?

```library(tidyverse);
library(plotly);
library(htmlwidgets);

df <- data.frame(x = 1:25, y = c(1:25 * 1:25))
gg <- ggplot(df,aes(x = x, y = y)) + geom_point()

# Save ggplotly as widget in file test.html
saveWidget(ggplotly(gg), file = "~/test.html")```

**Comment by rpkyle** [comment]
@heoa Hopefully the reply [here](https://github.com/plotly/dashR/pull/71#issuecomment-521221717) answered your underlying question (about how to embed `ggplotly` figures within a Dash for R app); if not, please let me know!

**Comment by heoa** [comment]
@rpkyle yes thank you, it would be super useful to have a collection of minimal working examples of using ggplot with dashR. I started the below thing

https://github.com/plotly/dashR/issues/118

which we could turn into documentation later.

**Comment by rpkyle** [comment]
Given that my earlier reply answered your initial question, I'm going to go ahead and close this one for now.
