### ISSUE TITLE
Fix live update demos

### ISSUE THREAD

**Issue by cpsievert** [plotly/dashR#12]
For some reason `POST /_dash-update-component` happens multiple times per update in these demos (e.g. https://github.com/plotly/dasher/blob/master/demo/live-updates.R). This could be an issue in dash-renderer, but perhaps I need to investigate how fiery/routr/httpuv resolves multiple scheduled requests.

**Comment by rpkyle** [comment]
We no longer have demos inside the `dash` package, and any issues with live demos should be raised in the gallery repo, so closing this one.
