### ISSUE TITLE
how to enable hot reloading?

### ISSUE THREAD

**Issue by Stalkcomrade** [plotly/dashR#124]
Is hot reloading absent?

It seems that by default hot reloading is disabled in Dash for R. Meanwhile, I failed to find any options to enable it like in python version (for instance, dev_tools_hot_reload_interval=5000).

**Comment by rpkyle** [comment]
@Stalkcomrade Hi Stanislav, thanks for your interest in Dash for R!

Now that we've implemented [support for multiple outputs](https://github.com/plotly/dashR/pull/119), hot reloading is just about the last major feature required to reach parity with Dash for Python. 

This is in progress, I'll be sure to keep you posted.

**Comment by rpkyle** [comment]
@Stalkcomrade I'm closing this in favor of https://github.com/plotly/dashR/issues/125, but will continue to update you as this progresses.
