### ISSUE TITLE
Need to implement hot reloading support in Dash for R

### ISSUE THREAD

**Issue by rpkyle** [plotly/dashR#125]
Dash for Python offers a lovely "hot-reloading" feature, as described in https://github.com/plotly/dash/issues/66, https://github.com/plotly/dash/pull/362, and https://github.com/plotly/dash-renderer/pull/73. Supporting this as in the Python implementation would require
- creating a hash at app initialization, and regenerating it on file change
- adding a route to serve the hash
- front-end hot reloading
- back-end hot reloading (reload the app by restarting the `fiery` session)
- adding parameters for the dev tools UI: `dev_tools_hot_reload`, `dev_tools_hot_reload_interval`, `dev_tools_hot_reload_watch_interval`, `dev_tools_silence_routes_logging`

On the Python side, we use the Flask debug reloader to reset the hash. `fiery` doesn't have native support for something like this feature, but it does allow "Custom Events" which can be manipulated to serve a similar purpose.

State-preserving hot reloading would be really nice to have, as noted in https://github.com/plotly/dash/issues/460, but it has not been implemented in Dash for Python yet either.

@alexcjohnson

**Comment by rpkyle** [comment]
@Stalkcomrade

**Comment by rpkyle** [comment]
Following discussions with @alexcjohnson, the PR to address this issue may be split into two parts:

- Part I: basic support (ensure backend functionality is working)
- Part II: full parity with Python implementation

Right now the following elements are working in some capacity:
- tracking file changes
- storing and generating the hash for the frontend
- routing for the reload hash, and returning modified file list
- cleaning up the logs using a custom logger so that `_reload-hash` chatter is omitted from logs
- enabling restarts of the `fiery` server, for full reloading of the app (e.g. if `app.R` is modified, or non-CSS files are added)

**Comment by rpkyle** [comment]
@StalkComrade This feature is ready for use and available in the `dev` branch if you'd like to test it out before the next version of the package is released! 🙂

**Comment by firasm** [comment]
Thanks @rpkyle, just to confirm is it 

```
library(devtools)
install_github("plotly/DashR", branch = "dev")
```

to get the dev version right?

**Comment by rpkyle** [comment]
> Thanks @rpkyle, just to confirm is it
> 
> ```
> library(devtools)
> install_github("plotly/DashR", branch = "dev")
> ```
> 
> to get the dev version right?

Hi @firasm ! Apologies for not catching this question sooner, but yes, that's the right branch -- I'd suggest installing with the command

```
library(devtools)
install_github("plotly/dashR", rev="dev")
```

The next release is imminent, and hopefully you'll be able to obtain the package from CRAN in the very near future. For now, ☝️ will do the trick 🙂

**Comment by rpkyle** [comment]
🌶 reloading is now available in `master`, closing issue.
