### ISSUE TITLE
Incorrect documentation of htmlButton

### ISSUE THREAD

**Issue by mjkallen** [plotly/dashR#126]
I have two comments related to the documentation of `htmlButton`:

1. htmlButton is [documented](https://dashr.plot.ly/dash-core-components/button) in the core components, which makes sense to me, but it is actually part of the _dashHtmlComponents_ R package. Maybe add a link from the documentation of the HTML components?
2. The documentation for htmlButton states that its initial value is `NULL`, but is actually `list(NULL)`. Below is the example from the documentation adapted to confirm this. The original example works fine because it actually does `as.character(list(NULL))` which is the string "NULL".

```r
library(dash)
library(dashCoreComponents)
library(dashHtmlComponents)

app <- Dash$new()

app$layout(
  htmlDiv(
    list(
      htmlDiv(dccInput(id="input-box", type="text")),
      htmlButton("Submit", id="button"),
      htmlDiv(id="output-container-button",
              children="Enter a value and press submit")
    )
  )
)

app$callback(
  output = list(id = "output-container-button", property = 'children'),
  params=list(input(id = "button", property = "n_clicks"),
              input(id = "input-box", property = "value")),
  function(n_clicks, value) {
    if (is.list(n_clicks)) {
      sprintf("'n_clicks' is a list of length %d", length(n_clicks))
    } else {
      sprintf("'n_clicks' is not a list and you have clicked the button %d time(s)", n_clicks)
    }
  }
)

app$run_server()
```
This app will initially display the following:
![htmlButton-example](https://user-images.githubusercontent.com/4612238/64248373-33163d80-cf11-11e9-9071-02e0c7c040da.png)

**Comment by rpkyle** [comment]
Thanks for taking the time to open this issue; both comments are accurate and helpful. 

> I have two comments related to the documentation of `htmlButton`:
> 
> 1. htmlButton is [documented](https://dashr.plot.ly/dash-core-components/button) in the core components, which makes sense to me, but it is actually part of the _dashHtmlComponents_ R package. Maybe add a link from the documentation of the HTML components?

This is a good suggestion, and something we should probably consider for the Python documentation as well, since [those pages](https://dash.plot.ly/dash-core-components/button) also lack a link from the Dash HTML Components docs.

> 2. The documentation for htmlButton states that its initial value is `NULL`, but is actually `list(NULL)`. Below is the example from the documentation adapted to confirm this. The original example works fine because it actually does `as.character(list(NULL))` which is the string "NULL".

I'll open a PR to address both items in our documentation, which will close this issue.

Dash callbacks fire when the app initially loads; in Dash for R, this is handled here:

https://github.com/plotly/dashR/blob/be16fb38bc56a1dc64b2d5f8b667de91bb034058/R/dash.R#L287-L289

The `do.call` function requires that the arguments each have a length greater than zero. Since `length(NULL)` is zero, this is somewhat problematic; currently, we wrap the initial value as `list(NULL)` to get around this issue. 

Thanks again for providing feedback!

**Comment by mjkallen** [comment]
You are very welcome and thanks for following up.

Can you refer me to the location of the documentation for Dash in R? I couldn't find it on GitHub and I may want to open a PR with fixes for typos and the like.

**Comment by rpkyle** [comment]
> You are very welcome and thanks for following up.
> 
> Can you refer me to the location of the documentation for Dash in R? I couldn't find it on GitHub and I may want to open a PR with fixes for typos and the like.

Of course! 🙂 Here's the link:

https://dashr.plot.ly

**Comment by alexcjohnson** [comment]
@rpkyle I think @mjkallen was asking where the code for it is - it's still hidden in the [`dashr-squashed` branch](https://github.com/plotly/dash-docs/tree/dashr-squashed) of `dash-docs`, right? We really need a plan to merge that...

**Comment by rpkyle** [comment]
@alexcjohnson 🤦‍♂ This is what I get for typing faster than I read.

I'll review the open PRs in that repo tomorrow, and try to open a PR for the mammoth merge.

**Comment by rpkyle** [comment]
@mjkallen Thanks again for opening this issue -- I've opened a PR to propose this change, will close this issue once resolved.

**Comment by rpkyle** [comment]
This issue was resolved in https://github.com/plotly/dash-docs/pull/889, redeploying docs this evening, closing issue now.
