### ISSUE TITLE
Couple of updates to documentation

### ISSUE THREAD

**Issue by firasm** [plotly/dashR#149]
Just wanted to point out a couple of typos I found in the documentation and [getting started pages]( https://dashr.plot.ly/getting-started).

1. For the first app, the documentation says:

`Rscript index.R`

But the app is actually called app.R above. So the fix should be:

`Rscript app.R`

2. `app$run_server()` is commented out on all the apps on the first page. I missed this when I was copy/pasting code

<img width="925" alt="Screen Shot 2019-11-27 at 9 10 44 PM" src="https://user-images.githubusercontent.com/2507459/69778761-6d7f2780-115a-11ea-9a60-66c7c0bf7639.png">

**Comment by rpkyle** [comment]
Thanks @firasm for the feedback! We're in the process of making these edits, I'll make a note here once plotly/dash-docs#716 is merged before closing the issue.

**Comment by rpkyle** [comment]
We've merged plotly/dash-docs#716, and the updated documentation is now available at https://dashr.plot.ly, so I'm closing this issue as resolved. Thanks to @firasm for bringing this to our attention.
