### ISSUE TITLE
Add some 'loading state' examples

### ISSUE THREAD

**Issue by cpsievert** [plotly/dashR#15]
https://community.plot.ly/t/mega-dash-loading-states/5687

**Comment by rpkyle** [comment]
Generated components for Dash now support loading states and a `Loading` component, as described here:

https://community.plot.ly/t/loading-states-and-loading-component/19650

...and the R version `dccLoading` component is here:

https://github.com/plotly/dash-core-components/blob/master/R/dccLoading.R

There are sample apps for R which take advantage of these features, so I'm closing this issue as addressed.
