### ISSUE TITLE
Interactive Visualizations Tutorial Error

### ISSUE THREAD

**Issue by ksedivyhaley** [plotly/dashR#154]
I'm trying to figure out how to implement linked interactivity in dashR. Since my app was unresponsive to clicks, I tested the first example in the [Tutorial](https://dashr.plot.ly/interactive-graphing) (starting from "Here's an simple example that prints these attributes to the screen") and discovered that this app does not execute properly when I copy-paste and run that exact code. While the tutorial page itself updates with the following when clicked:

```
{
  "points": [
    {
      "curveNumber": 0,
      "pointNumber": 0,
      "pointIndex": 0,
      "x": 1,
      "y": 4,
      "customdata": "c.a",
      "text": "a"
    }
  ]
}
```

... the app run locally does not update when clicked. Otherwise the app displays normally.

Would appreciate any assistance. Running Windows 10, R version 3.6.1, dash 1.0.0.

**Comment by firasm** [comment]
In case someone else finds this and you aren't able to run the code in the docs because the `.csv` file couldn't be found, here is the correct link: https://github.com/plotly/dash-docs/blob/dashr-squashed/dashr/chapters/callbacks/examples/indicators.csv.

Just download the file and adjust the path to access this file locally

**Comment by ksedivyhaley** [comment]
Update on this: after checking the second example and finding it runs fine with access to the csv code provided with @firasm , I re-tested the first example, and observed in addition to the unresponsive app, the error: 

> error: could not find function "prettify"

printing to the powershell in which the app was launched. The addition of `library(jsonlite)` to the beginning of the app file results in a working dash app.

I am not certain whether this is the sole cause of the initial issue (I could have overlooked the error in my powershell Sunday evening) or whether you fixed something else (in which case, thanks!) but it looks like the only thing the documentation could use right now is adding additional `library(jsonlite)` call at the beginning of the example to make the dependency clear for anyone trying to run this code from their own machine.

**Comment by rpkyle** [comment]
Thanks again @ksedivyhaley for pointing this out; we've updated the documentation to reflect this suggestion. Closing as resolved.
