### ISSUE TITLE
Incorrect RangeSlider Documentation

### ISSUE THREAD

**Issue by ksedivyhaley** [plotly/dashR#155]
I noticed that the `dccRangeSlider()` documentation in the [Components Gallery](https://dashr.plot.ly/dash-core-components) appears to be in error with respect to the marks argument. Based on this item in the documentation:

```
library(dashCoreComponents)
  dccRangeSlider(
  marks = lapply(-5:7, function(x){paste("Label", x)}),
  min = -5,
  max = 6,
  value = list(-3,4)
  ) 
```

I attempted to implement the following:

```
yearSlider <- dccRangeSlider(
  marks = lapply(unique(gapminder$year), function(x){paste("", x)}),
  min = 1952,
  max = 2007,
  step=5,
  value = list(1952, 2007)
)
```

But discovered that this did not produce any marks. Based on other examples [located in the further RangeSlider examples](https://dashr.plot.ly/dash-core-components/rangeslider), I tried the following, which did work:

```
yearMarks <- lapply(unique(gapminder$year), as.character)
names(yearMarks) <- unique(gapminder$year)
yearSlider <- dccRangeSlider(
  marks = yearMarks,
  min = 1952,
  max = 2007,
  step=5,
  value = list(1952, 2007)
)
```

**Comment by rpkyle** [comment]
Hi @ksedivyhaley -- thanks a lot for opening this issue, and for noting the incorrect entries in the documentation. 

The code you shared looks right to me, and @HammadTheOne and I are in the process of redeploying the docs to include it. I'll keep this issue open until that's done.

**Comment by HammadTheOne** [comment]
I made a slight change and this will be fixed with an updated example once https://github.com/plotly/dash-docs/pull/732 is merged. It should address the marks not showing up on all the values, and also make it a bit easier to base off of for your own implementations.

**Comment by rpkyle** [comment]
plotly/dash-docs#32 has been merged; closing. Thanks again @ksedivyhaley for filing this issue!
