### ISSUE TITLE
Tools for debugging components

### ISSUE THREAD

**Issue by cpsievert** [plotly/dashR#16]
It's hard to know when/why a component is 'mis-specified'. Furthermore, my current debugging process is not ideal (`app$layout_set(component); app$layout_get(); app$run_server()`). Some ideas for improvements:

1. Printing a component could spin up a simple dash app with just that component.
2. Provide a 'debugging mode/option' where client side errors are listed in a pop-up (the current generic `Error loading dependencies` message is not helpful and most folks won't know to open their browser's dev tools)
3. Automatically type check arguments in R using the components `propTypes` definition

**Comment by rpkyle** [comment]
Quite a lot of work has been undertaken in `dash-renderer` via the dev tools UI, and through the use of `PropTypes.js`. This is now available to all Dash backends "for free", and any future work on improving debugging is likely to be handled within JavaScript. Closing as resolved.
