### ISSUE TITLE
Config-aware relative path support for Dash for R

### ISSUE THREAD

**Issue by HammadTheOne** [plotly/dashR#170]
Currently Dash for R lacks support for config-aware relative paths which exists on Dash for Python. This feature should be added for parity and address different path URLs for apps running locally or deployed on a server. 

Details on the Python version of the feature that we're hoping to emulate with Dash for R can be found in plotly/dash-core#78.

**Comment by rpkyle** [comment]
🎉This feature was merged into the latest release; closing now.
