### ISSUE TITLE
Maximum number of plotly plots in Rmarkdown

### ISSUE THREAD

**Issue by CarolineXGao** [plotly/dashR#188]
It seems that we cannot include more than 15 plotly 3D plots in a Rmarkdown file.  Here is the test code :

---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
plot<-list() 
data<-list()

x <- 1:5/10
y <- 1:5

library(plotly)
for (i in 1:20){
      z <- x %o% y
      z <- z + .2*z*runif(25) - .1*z
      data[[i]]= z 
      plot[[i]]<-plot_ly(x=x,y=y,z=data[[i]], type="surface")
}

htmltools::tagList(plot)

```
Thanks!!!!! 

Best,
Caroline

**Comment by alexcjohnson** [comment]
Yes, that's true. It's a browser limitation in fact, that generally you cannot create more than 16 WebGL contexts in one tab. And some of our trace types use 2 or 3 separate contexts for a single graph, so the limit would be dropped down to 8 or 5 charts. See https://github.com/plotly/plotly.js/issues/2333 for more info, one potential work-around (removing off-screen graphs) and one potential long-term solution (`multi-regl`). This solution isn't part of our existing roadmap unless someone is interested in sponsoring it.

I believe multiple graphs within one plot *do* share contexts, so you could try using subplots.

**Comment by CarolineXGao** [comment]
Thanks very much.  

Unfortunately, I have more than 16 contexts. Using subplots didn't really help.  I guess this will become more and more of an issue when people started to embed more complicated plotly plots in their Rmarkdown files. Will be looking forward to future resolutions. 

Best, 

Caroline

**Comment by sebidelamata** [comment]
Any follow up on this?
