### ISSUE TITLE
Implement exceptions.PreventUpdate

### ISSUE THREAD

**Issue by cpsievert** [plotly/dashR#25]
https://github.com/plotly/dash/pull/190

https://github.com/plotly/dash/commit/fd2f353814cbccc8fc9df378d780ebc96d7c136f
https://github.com/plotly/dash/commit/ad92fa31f0388813ba7695ef108504397c8c0ba2

**Comment by rpkyle** [comment]
@nicolaskruchten @alexcjohnson I was talking with @kphans not that long ago, and he asked whether this was on the list of features to support. We haven't discussed this item specifically.

It exists in Dash for Python, so I am assuming that it is?

**Comment by alexcjohnson** [comment]
Definitely should be on the list. Also see `dash.no_update` https://github.com/plotly/dash/pull/680 which is only strictly necessary when we get to multi outputs but is a nice alternative to raising an error even for single outputs.

**Comment by rpkyle** [comment]
> Definitely should be on the list. Also see `dash.no_update` [plotly/dash#680](https://github.com/plotly/dash/pull/680) which is only strictly necessary when we get to multi outputs but is a nice alternative to raising an error even for single outputs.

We discussed the implementation of `PreventUpdate` in R, and I believe the initial plan is to use something like `no_update`. I'm working on that today, will attempt to draft a PR by tomorrow.
