### ISSUE TITLE
Dash does not work without explicitly loading {dashHtmlComponents}

### ISSUE THREAD

**Issue by daattali** [plotly/dashR#260]
It seems that loading {dashHtmlComponents} is a requirement for a dash app to work, and that namespacing it doesn't work.

The below app works:

```
library(dash)
library(dashHtmlComponents)
app <- Dash$new()
app$layout(htmlDiv("test"))
app$run_server()
 ```

But the following doesn't render and results in javascript errors:

```
library(dash)
app <- Dash$new()
app$layout(dashHtmlComponents::htmlDiv("test"))
app$run_server()
 ```

**Comment by alexcjohnson** [comment]
@daattali post https://github.com/plotly/dashR/pull/243 (which hasn't been published yet) there shouldn't even be a `dashHtmlComponents` package anymore - is that included in the starting point you're working with? Is this only an issue with `dashHtmlComponents` or is it also a problem if you reference other packages (core like `dashCoreComponents` or non-core like `dashBio`) via namespace?

**Comment by daattali** [comment]
Haven't checked the other packages. I'm using latest CRAN version, but shouldn't be an issue to modify code once dashHtmlComponents gets unified.

**Comment by daattali** [comment]
Can confirm my code chunk above does work in the `dev` branch.
