### ISSUE TITLE
help~I want update this packages,what should i do ?

### ISSUE THREAD

**Issue by zulinwu** [plotly/dashR#276]
Hello! Now I want to update this packages to last version in R --dashHtmlComponents, dashCoreComponents, and dashTable.What should I do? I just update 'dashR' in github. think you very much!

**Comment by HammadTheOne** [comment]
Hi @zulinwu, I just wanted to clarify this issue, If you would like to make an update to this package, you can open a PR off of the `dev` branch, and make your changes to that before they're merged. 

There aren't any strict contributing guidelines set for this project at the moment, but the tests should pass and the PR must be reviewed by code owners before any changes can be merged. 

Feel free to open this issue if that does not answer your question.
