### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by RichardJActon** [plotly/dashR#287]
The [introduction in the docs](https://dash.plotly.com/r/introduction) states:

> Dash is an open source library released under the permissive MIT license.

but the [license file in this project](https://github.com/plotly/dashR/blob/master/LICENSE) just states: YEAR: 2021 COPYRIGHT HOLDER: Plotly, Inc.

Is this library MIT licensed & if so could that be clarified by including the license in the repo?

**Comment by alexcjohnson** [comment]
Thanks @RichardJActon - the intent is definitely the MIT license.

@HammadTheOne can you say more about what's going on here? The MIT license was replaced by this 2-line thing in https://github.com/plotly/dashR/commit/3e2672333ab7c7ebabe454c0e73790ca8e1e0b20 labeled "CRAN submission updates" - is it possible to make CRAN happy and also have the correct license here?

**Comment by HammadTheOne** [comment]
Sure, I can clarify this. The license itself is set with the package description, and it points to the LICENSE text, which only includes the year and copyright holder to satisfy CRAN's checks. https://github.com/plotly/dashR/blob/22ea495581c65d94e61f9bd5f31a981a10c235a0/DESCRIPTION#L30

To be a bit more explicit about it, I can add a LICENSE.md with a full copy of the MIT license and include it in the `.Rbuildignore` so it doesn't affect any future CRAN submissions.

**Comment by alexcjohnson** [comment]
That makes sense - thanks @HammadTheOne! Yes, let's add a LICENSE.md as you suggest, and maybe at the top of that file add a comment like "Note: per CRAN rules the file LICENSE has specific requirements, so we include this file LICENSE.md with the complete license text."

**Comment by HammadTheOne** [comment]
Closing via [5c5f60f](https://github.com/plotly/dashR/commit/5c5f60fd3d5773632c8a452fa432e8e96570236b) made on the `dev` branch.

**Comment by alexcjohnson** [comment]
Thanks @HammadTheOne 🙇
