### ISSUE TITLE
CRAN release strategy

### ISSUE THREAD

**Issue by cpsievert** [plotly/dashR#31]
Since CRAN won't let you import/suggest non-CRAN packages, these packages will have to be submitted first (might want to add a comment that these are useful by themselves, but will provide a foundation for downstream submissions):

~https://github.com/plotly/dashTranspileR~
https://github.com/plotly/dash-html-components
https://github.com/plotly/dash-core-components
~https://github.com/plotly/dashHtmlwidgetComponent~

Then these:

https://github.com/plotly/dash
~https://github.com/plotly/dashAuthR~

**Comment by kozo2** [comment]
Please let me know if there is anything that I can help with (CRAN release).

**Comment by rpkyle** [comment]
Thanks @kozo2! 🙂

At the moment I'm finishing up with adding a few more examples to our packages, and awaiting a slight modification in the way we name the JavaScript dependencies to satisfy CRAN's filename portability requirements.

**Comment by rpkyle** [comment]
Superseded by another issue; closing as CRAN submission of `dash` is now underway, and the component libraries are already available. Thanks again to @kozo2 for the offer of help!
