### ISSUE TITLE
Asset serving

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dashR#46]
There's a surprisingly deep and complicated pipeline behind the generation of the component `<script>` tags that Dash drops into the `index.html` which it returns to clients on first load.

Minimally, DashR needs to serve `script` tags for *locally served* JS bundles that match the component libraries that are loaded in the initial layout.

This is on the critical path for #45

**Comment by rpkyle** [comment]
>Minimally, DashR needs to serve script tags for locally served JS bundles that match the component libraries that are loaded in the initial layout.

This is currently working. However, this is in the set of _minimal, but not sufficient_ elements related to asset serving in Dash. Here's the list of features that must be available for the initial release:
- Assets folder auto resolution (`/assets`) at the root of the project by default.
- Assert that `assets` folder may be passed as parameter
- Assert that JS/CSS files in `/assets` are served in the index
- Assert that an ignore filter exists and works for served assets
- Assert that assets are cached by the browser, and uncached when modified
- Assert that all files in `/assets` are served statically
- Assert that the assets URL respects routes/requests pathname prefix
- Assert that easy retrieval of assets URLs is possible: `get_asset_url(asset)` should return a ready-to-insert URL string
- Assert that if a `favicon.ico` is found in the assets folder, it be served as the title icon of the page.
