### ISSUE TITLE
hoverData

### ISSUE THREAD

**Issue by TahiriNadia** [plotly/dashR#61]
# In Python version
```
dcc.Graph(
            id='crossfilter-indicator-scatter',
            hoverData={'points': [{'customdata': 'Japan'}]}
        )
....
@app.callback(
    dash.dependencies.Output('y-time-series', 'figure'),
    [dash.dependencies.Input('crossfilter-indicator-scatter', 'hoverData'),
     dash.dependencies.Input('crossfilter-yaxis-column', 'value'),
     dash.dependencies.Input('crossfilter-yaxis-type', 'value')])
def update_x_timeseries(hoverData, yaxis_column_name, axis_type):
    dff = df[df['Country Name'] == hoverData['points'][0]['customdata']]
    dff = dff[dff['Indicator Name'] == yaxis_column_name]
    return create_time_series(dff, axis_type, yaxis_column_name)
```

# In R version
```
dccGraph(
        id = 'crossfilter-indicator-scatter',
        hoverData = list(points = list(list(customdata = 'Japan')))
      )
....
app$callback(
  output = list(id='y-time-series', property='figure'),
  params = list(input(id='crossfilter-indicator-scatter', property='hoverData'),
                input(id='crossfilter-yaxis-column', property='value'),
                input(id='crossfilter-yaxis-type', property='value')),
  function(hoverData, yaxis_column_name, axis_type) {
    dff <- df[df[["Country_Name"]] %in% hoverData$points[[1]]$customdata, ]
    dff <- dff[dff[["Indicator_Name"]] %in% yaxis_column_name, ]
    return(create_time_series(dff, axis_type, yaxis_column_name))
  }
)
```

# Error message
```
error: unused argument (points = list(list("Japan")))
```

# Documentation needed
[Graph.react.js](https://github.com/plotly/dash-core-components/blob/master/src/components/Graph.react.js)

**Comment by rpkyle** [comment]
Thanks for posting @TahiriNadia; I'll take a look.

**Comment by TahiriNadia** [comment]
## To validate
Many errors due to `/_dash-update-component` such as:
- `hoverData`
- `clickData`
- `selectedData`
- `relayoutData`

... ERROR given:
`error: unused argument ...`

I'm supprose the error is happen during `update` page?

**Comment by TahiriNadia** [comment]
The `dccGraph` component has four attributes that can change through user-interaction: `hoverData`, `clickData`, `selectedData`, `relayoutData`. These properties update when you hover over points, click on points, or select regions of points in a graph.

**Comment by rpkyle** [comment]
The components are "transpiled" from JSON just as they are in Python, so I'd be surprised if the `dccGraph` component was the issue here. I'm in the process of walking through the app code to understand the error message you reported, but I'm going to finish up with asset serving first, and then dive in for real.

**Comment by TahiriNadia** [comment]
The relationship of all these inputs are multiple-value, see Kevin's app example.

**Comment by rpkyle** [comment]
> The relationship of all these inputs are multiple-value, see Kevin's app example.
I've rebuilt the package with Alex's edit so @TahiriNadia and Kevin can test. 🤞
