### ISSUE TITLE
DccRangeSlider Seems to not be able to set predefined values

### ISSUE THREAD

**Issue by KPhans** [plotly/dashR#70]
htmlDiv(
        list(
          htmlP('Filter by construction date (or select range in histogram):'),
          dccRangeSlider(
            id='year_slider',
            min=1960,
            max=2017,
            value= list(1990,2017)
          )
        ),
        style=list('margin-top' = '20')
      )
would return a range slider not set to the values wanted. Could be a core problem?

**Comment by KPhans** [comment]
@rpkyle @NadiaTahiri

**Comment by rpkyle** [comment]
Hmm, looks OK to me (code below)?

![image](https://user-images.githubusercontent.com/9809798/55168547-64f8cc00-5149-11e9-9e24-adfda4c19fa1.png)

```
library(dashR)
library(dashHtmlComponents)
library(dashCoreComponents)

app <- Dash$new(external_stylesheets = "https://codepen.io/chriddyp/pen/bWLwgP.css")

app$layout_set(
  htmlDiv(list(
      dccRangeSlider(id = 'my-range-slider',
                     min = 1980,
                     max = 2020,
                     step = 0.5,
                     value = list(1990, 2017)),
      htmlDiv(id = 'output-container-range-slider')
  )
  )
)

app$callback(output=list(id='output-container-range-slider', property='children'),
             params=list(
               input(id='my-range-slider', property='value')),
             function(value)
             {
               return(sprintf("You have selected %s", paste(value, collapse = ", ")))
             }
)

app$run_server()
```

**Comment by rpkyle** [comment]
☝️ this app is my crude rewrite of the first one seen here:
https://dash.plot.ly/dash-core-components/rangeslider

**Comment by KPhans** [comment]
thanks ryan, just looked at this.

**Comment by rpkyle** [comment]
Kevin and I chatted about this, he made a change to his DashR app code, and `rangeSlider` behaved as expected. The sample DashR app code above demonstrates that the slider is initially set to the defined values, so behaviour is as expected.
