### ISSUE TITLE
Slicer -- min and max issues (Need indexes?)

### ISSUE THREAD

**Issue by TahiriNadia** [plotly/dashR#80]
#### _Code:_
```{python}
import dash_core_components as dcc

dcc.RangeSlider(
    marks={i: 'Label {}'.format(i) for i in range(-5, 7)},
    min=-5,
    max=6,
    value=[-3, 4]
)
```
#### _Result:_
![Screen Shot 2019-04-08 at 1 36 48 PM](https://user-images.githubusercontent.com/19578926/55744823-d404d900-5a03-11e9-8820-ef41a2fda7ac.png)

#### _Code:_
```{r}
library(dashCoreComponents)

dccRangeSlider(
    marks=c(paste("Label", -5:6)),
    min=-5,
    max=6,
    value=list(-3, 4)
)
```

#### _Result:_
![Screen Shot 2019-04-08 at 1 37 07 PM](https://user-images.githubusercontent.com/19578926/55744836-dcf5aa80-5a03-11e9-9655-f9e0366904da.png)

**Comment by alexcjohnson** [comment]
`c(paste("Label", -5:6))` doesn't look like the R equivalent of
`{i: 'Label {}'.format(i) for i in range(-5, 7)}`

I think you need something like `list('-5'='label -5', '-4'='label -4', ...)` instead. Perhaps:
`setNames(c(paste("Label", -5:6)), -5:6)`?

**Comment by alexcjohnson** [comment]
That said the fact that we'll render labels beyond the range of the slider seems like a bug - @TahiriNadia would you mind making an issue for this over at https://github.com/plotly/dash-core-components/issues?

**Comment by rpkyle** [comment]
> `c(paste("Label", -5:6))` doesn't look like the R equivalent of
> `{i: 'Label {}'.format(i) for i in range(-5, 7)}`
> 
> I think you need something like `list('-5'='label -5', '-4'='label -4', ...)` instead. Perhaps:
> `setNames(c(paste("Label", -5:6)), -5:6)`?

Nice! The latter snippet worked for me.

@TahiriNadia As @alexcjohnson noted, the label rendering problem is a `dash-core-components` problem rather than something to fix in DashR, but we should open an issue for this there anyway.

If this resolves your problem, feel free to close the issue 🙂

**Comment by TahiriNadia** [comment]
Thank you @alexcjohnson for your ideas. I tried and gave some modifications to convert into a list, here my code:

### Code:
```
dccRangeSlider(
    marks=as.list(setNames(c(paste("Label", -5:6)), -5:6)),
    min=-5,
    max=6,
    value=list(-3, 4)
)
```

### Result:
![Screen Shot 2019-04-10 at 10 28 23 AM](https://user-images.githubusercontent.com/19578926/55887561-b6f31600-5b7b-11e9-960a-9df9f9d15c34.png)
