### ISSUE TITLE
DashR lacks a before_first_request hook

### ISSUE THREAD

**Issue by rpkyle** [plotly/dashR#89]
In Dash for Python, tasks intended to begin before app serving occurs may use the `before_request_hook`:

https://github.com/plotly/dash/commit/736469dc11f455831115c66bc225a6ca428a154c

Currently, DashR provides no comparable method in the `Dash` class. For the sake of parity, it should exist in both backends.

**Comment by alexcjohnson** [comment]
TBH I'm not sure why `_setup_server` needs to happen with a server available at all, I don't see anything in there involves the server...

Anyway `before_request_hook` is a `Flask` method that we're using internally, absent a clear use case I don't see how it's adding functionality for dash users so I wouldn't worry about porting it to dashR.

**Comment by rpkyle** [comment]
> TBH I'm not sure why `_setup_server` needs to happen with a server available at all, I don't see anything in there involves the server...
> 
> Anyway `before_request_hook` is a `Flask` method that we're using internally, absent a clear use case I don't see how it's adding functionality for dash users so I wouldn't worry about porting it to dashR.

Hmm. And there won't be any issues in multi-user apps if users run statements prior to executing their Dash apps within the global environment?

**Comment by alexcjohnson** [comment]
A multi-user app still just has one back-end process - or, if we've scaled to multiple processes, they all start up exactly the same way. Writing statements that execute prior to creating the app object is a standard pattern at this point, like to load data to be used as fixed global state.
